In [1]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/tmdb/tmdb-movie-metadata/tmdb_5000_movies.csv
/kaggle/input/datasets/tmdb/tmdb-movie-metadata/tmdb_5000_credits.csv

In [2]:
import pandas as pd
credits = pd.read_csv('/kaggle/input/datasets/tmdb/tmdb-movie-metadata/tmdb_5000_credits.csv')
movies = pd.read_csv('/kaggle/input/datasets/tmdb/tmdb-movie-metadata/tmdb_5000_movies.csv')


print("TMDB Movies:", movies.shape)
print("TMDB Credits:", credits.shape)

TMDB Movies: (4803, 20)
TMDB Credits: (4803, 4)

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies.merge(credits,on='title').head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.merge(credits,on='title').shape

(4809, 23)

In [7]:
movies = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id',
    how='inner',
    suffixes=('', '_credits')
)

In [8]:
movies.shape

(4803, 24)

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  movie_id              4803 non-null   int64
 21  title_credits         4803 non-null   object
 22  cast                  4803 non-null   object
 23  crew                  4803 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [10]:
# genres
# id
# keywords
# overview
# title
# cast
# crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies.head(1)

In [ ]:
movies.isnull().sum()

In [ ]:
movies = movies.dropna().reset_index(drop=True)

In [ ]:
movies.duplicated().sum()

In [ ]:
movies.iloc[0].genres

In [ ]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# we want in this format - ['Action','Adventure','Fantasy','Science Fiction']
import ast
def extract_name(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [ ]:
extract_name('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

In [ ]:
movies['genres'] = movies['genres'].apply(extract_name)

In [ ]:
movies.iloc[0].keywords

In [ ]:
movies['keywords'] = movies['keywords'].apply(extract_name)

In [ ]:
movies.head(1)

In [ ]:
movies.iloc[0].cast

In [ ]:
def extract_top_3_names(obj):
    l=[]
    count=0
    for i in ast.literal_eval(obj):
        l.append(i['name'])
        count+=1
        if(count == 3):
            break
    return l

In [ ]:
movies['cast'] = movies['cast'].apply(extract_top_3_names)

In [ ]:
movies.head(1)

In [ ]:
movies.iloc[0].crew

In [ ]:
def extract_director_name(obj):
    l = []
    for i in ast.literal_eval(obj):
        if(i['job'] == 'Director'):
            l.append(i['name'])
            break
    return l

In [ ]:
movies['crew'] = movies['crew'].apply(extract_director_name)

In [ ]:
movies.head(1)

In [ ]:
movies['overview'][0]

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head(1)

In [ ]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies.head()

In [ ]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
movies.head()

In [ ]:
new_df = movies[['movie_id','title','tags']].copy()

In [ ]:
new_df.head()

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [ ]:
new_df.head()

In [ ]:
new_df['tags'][0]

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

In [ ]:
new_df['tags'][0]

In [ ]:
new_df['tags'][1]

In [ ]:
new_df['tags'][2]

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [ ]:
stem('a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. while m battles political forces to keep the secret service alive, bond peels back the layers of deceit to reveal the terrible truth behind spectre. action adventure crime spy basedonnovel secretagent sequel mi6 britishsecretservice unitedkingdom danielcraig christophwaltz léaseydoux sammendes'
)

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features = 5000,stop_words='english')

In [ ]:
vectors_bow = bow.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors_bow

In [ ]:
vectors_bow[0]

In [ ]:
bow.get_feature_names_out()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
bow_similarity = cosine_similarity(vectors_bow)

In [ ]:
bow_similarity.shape

In [ ]:
bow_similarity[0]

In [ ]:
bow_similarity[1]

In [ ]:
def recommend(movie,top_n):
    matches = new_df[new_df['title'].str.lower() == movie.lower()]

    if len(matches) == 0:
        print("Movie not found!")
        return
    
    # Get the index of the movie
    movie_index = matches.index[0]
    distances = bow_similarity[movie_index]
    
    # Get top_n recommendations (skipping the first one as it is the movie itself)
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
    for i in movie_list:
        # Correctly access the title using iloc[index]
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Avatar',10)

In [ ]:
print("Total rows:", len(movies))

print("Duplicate movie IDs:",
      movies['movie_id'].duplicated().sum())

print("Unique movie IDs:",
      movies['movie_id'].nunique())

In [ ]:
movies[movies['movie_id'].duplicated(keep=False)][
    ['movie_id', 'title']
].sort_values('movie_id')

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
pickle.dump(bow_similarity,open('similarity.pkl','wb'))